### ISSUE TITLE
Filenaming problem in Windows 10

### ISSUE THREAD

**Issue by JavierSanzCruza** [sisinflab/elliot#8]
Hello,

Following the instructions provided in the documentation, I have succesfully installed the Elliot library using Conda v.4.8.2. and Python 3.7.10 on a Windows 10 system. 

However, I have found some problems at the moment of executing some experiments on the framework. The library seems to work finely when I use an algorithm without hyperparameters (as it happens, for instance, with the MostPop algorithm). However, due to how the weight files are named, it does not allow me to execute algorithms with hyperparameters, such as UserKNN or ItemKNN.

At the moment, the project tries to create a directory or a file (I think is the first one), named `algorithm_hyper1:val1_hyper2:val2_..._hyperN:valN` where hyperX is the name of the X-th hyperparameter, valX is the value of such hyperparameter and N is the final number of hyperparameters. 

However, Windows does not allow colons in the names of files/folders, so it stops, and returns an OSError as the one I show below:
![imagen](https://user-images.githubusercontent.com/13061902/114735560-94d19700-9d45-11eb-9f2a-44ed9208e641.png)

Can anything be done to solve this?

**To reproduce**
I share the configuration file that I used:
![imagen](https://user-images.githubusercontent.com/13061902/114735988-fe51a580-9d45-11eb-9c8b-1dcde07a5075.png)

Thanks in advance.

**Comment by scne** [comment]
Hi @JavierSanzCruza,
the last version of Elliot solve several bugs. Among of them also your is fully managed.
